### ISSUE TITLE
school logos are cut in the dropdown menu

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#153]

**Comment by EmberShan** [comment]
Problem: 
![Image](https://user-images.githubusercontent.com/54587893/173240811-9d6ae349-514c-441e-a474-1289b00e3e4a.png)

**Comment by elVengador** [comment]
Now is solved
![Image](https://user-images.githubusercontent.com/27080940/173963236-bb130d69-b1ae-482e-b987-59f95099fd47.png)

**Comment by elVengador** [comment]
also logos in  CHIPS in PR #201
