### ISSUE TITLE
add tooltips for each link in nav bar and footer and open links in a new tab

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#170]

**Comment by elVengador** [comment]
in Node? 

![Image](https://user-images.githubusercontent.com/27080940/173628400-70da40ff-86d9-4ca8-98e9-7407c3a2cf1e.png)

**Comment by EmberShan** [comment]
Yes, on the node website, nav bar links should have tooltips just like https://1cademy.us/home
