### ISSUE TITLE
nav search bar issue

### ISSUE THREAD

**Issue by yashgandhi303** [ImanYZ/VisualExp#177]
https://user-images.githubusercontent.com/35921466/173680857-429be438-221c-43b7-ac73-307268245b15.mp4

**Comment by elVengador** [comment]
@yashgandhi303 I cant see the bug, can you explain me please?

**Comment by yashgandhi303** [comment]
initially the search bar in nav appears but then disappears. that
flickering shouldn’t happen

**Comment by elVengador** [comment]
ok, I will solve, thank you
