### ISSUE TITLE
Clicking feedback icon creates a white space under the footer

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#189]

**Comment by EmberShan** [comment]
I am using Firefox on Mac. See the error in the following video 
https://user-images.githubusercontent.com/54587893/173896882-ae725346-598e-4deb-833e-5c60de1cc630.mov

**Comment by elVengador** [comment]
Now feedback is positioning in the top
![Image](https://user-images.githubusercontent.com/27080940/173932222-eb549618-4cdb-4b22-a86e-9eaa41f40e66.gif)
