### ISSUE TITLE
Two "wikipedia" references

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#257]
When searching `Wikipedia` in the reference filter, there are two wiki references: `Wikipedia` and `WikipediA`

![Image](https://user-images.githubusercontent.com/54587893/175041423-5ec440a4-1b58-4591-9c4d-ce67041e7a8b.png)

The `WikipediA` only has one section, and the node in the search result is referencing  `Wikipedia`, not `WikipediA`
Node URL here:` https://node.1cademy.us/sigmoidlogistic-function/jA5VVgI4wW4rP79Xh7TX`

![Image](https://user-images.githubusercontent.com/54587893/175041662-62eb2f59-4775-439c-813a-e35119125246.png)

**Comment by elVengador** [comment]
I checked all the flow:
- indexing reference data to build the autocomplete
- how get references in NodeItem
I think there is a inconsistence in database
