### ISSUE TITLE
On FireFox, some nodes would have a long white space below the footer.

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#264]
I only found this issue on FireFox (both on Mac and Win), but not on Chrome. 

On FireFox, do the following: 
Click the `Behavioral Neuroscience` node on this page: `https://node.1cademy.us/?title=behavioral-neuroscience&id=EotqbmSg4XdYq5U5BQCP&q=Behavioral+Neuroscience&page=1`

Problem shown in this video: 
https://user-images.githubusercontent.com/54587893/175074324-3e2621ab-2c6e-4f3a-b6ae-2d98d6f3072f.mov

**Comment by elVengador** [comment]
error: https://firefox-source-docs.mozilla.org/performance/scroll-linked_effects.html
solved in #230, when change position from feedback button
