### ISSUE TITLE
Change the background opacity for the feedback form fields when not filled

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#291]
reduce the opacity of the red background to `0.2`

Change this: 

![Image](https://user-images.githubusercontent.com/54587893/175617923-02d17bed-7857-4a79-9f6a-84f69f48589e.png)

result: 

![Image](https://user-images.githubusercontent.com/54587893/175617991-9c23664c-bf9d-46c2-9a5f-3916be414890.png)

**Comment by elVengador** [comment]
Now is in this way:

![Image](https://user-images.githubusercontent.com/27080940/191136672-c5770f1b-86fc-42bd-babf-10191d8da3ee.png)

Do you want to apply that styles when error happend in all inputs?
