### ISSUE TITLE
Institutions logos not showing in chips on search page

### ISSUE THREAD

**Issue by EmberShan** [ImanYZ/VisualExp#91]

**Comment by EmberShan** [comment]
The problem: 
![Image](https://user-images.githubusercontent.com/54587893/172027090-1e181470-e824-4958-8260-f81b2fc3eef4.png)


It should show the logos just like on the single node page: 
![Image](https://user-images.githubusercontent.com/54587893/172027086-d9b72c3a-3acb-468e-b77e-dea2eee61c5c.png)

**Comment by elVengador** [comment]
It show the first letter from university while is downloading the image, @EmberShan confirm please if this is the correct functionality to close the issue
![Image](https://user-images.githubusercontent.com/27080940/172466513-4c522626-65f1-4f8f-be99-9edba3bdb62e.gif)
